version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=seo_project_db
      - DB_USER=postgres
      - DB_PASS=Maneth99
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=seo_project_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Maneth99
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
